### ISSUE TITLE
초급 56) internal/modules/cjs/loader.js:583

### ISSUE THREAD

**Issue by pencilpie** [js-200/js-200-examples#17]
안녕하세요.

<초급 56 모듈 시스템 이해하기>에서 에러가 발생하는데요.

제가 윈도우 운영체제를 사용하고 있는데, 환경변수에 path를 이것저것 추가해봤는데 해결이 안되네요.

전체 에러 메시지는 아래와 같습니다.

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './hello.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [stdin]:3:14
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at evalScript (internal/bootstrap/node.js:587:27)
[Finished in 1.214s]

**Comment by shwldus3** [comment]
초급56 예제는 Note에 기재된된대로 index.html를 라이브서버로 실행해주세요.
자세한 설명이 부족하여 발생된 부분이라.. 2판에서 이부분 보완하겠습니다. 감사합니다.
